name: Breatchwatcher 24/7

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '147'

      - name: Clone Repositories
        run: |
          git clone --branch ${{ github.event_name }} https://github.com/nuxeo/nuxeo-tools-support-priv
          cd nuxeo-tools-support-priv
          git submodule update --init --recursive

      - name: Checking 24/7 Tickets
        run: |
          cd nuxeo-tools-support-priv
          cd tickets/stages
          ./execute_stage.sh tickets_at_risk weekend
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}

      - name: Send Notifications
        run: |
          if [ -n "$ticketsResults" ]; then
            notifsList=($ticketsResults)
            echo "Sending ${#notifsList[@]} notification(s) to ${SLACK_CHANNEL}..."
            for notif in "${notifsList[@]}"; do
              echo "Sending ###${notif}###"
              curl -X POST -H "Content-type: application/json" -d '{"channel": "'${SLACK_CHANNEL}'", "color": "#FF0000", "text": "'${notif}'"}' https://slack.com/api/chat.postMessage?token=${{ secrets.SLACK_TOKEN }}
            done
          else
            echo "No notification to send."
          fi
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
